param(
  [string]$ProjectRoot = (Resolve-Path "$PSScriptRoot\.."),
  [string]$OutFile = "docs/PROJECT_DOCUMENTATION.md"
)

$ErrorActionPreference = 'Stop'

$root = Resolve-Path $ProjectRoot
$fullOut = Join-Path $root $OutFile

New-Item -ItemType Directory -Force -Path (Split-Path $fullOut) | Out-Null

function Write-Line([string]$s) {
  Add-Content -Path $fullOut -Value $s -Encoding UTF8
}

# Reset output
Set-Content -Path $fullOut -Value "# Project Documentation (Generated Index)" -Encoding UTF8
Write-Line ""
Write-Line "> Generated on: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Line "> Root: $root"
Write-Line ""

Write-Line "## Documentation entry point"
Write-Line "- See: [docs/README.md](./README.md)"
Write-Line ""

Write-Line "## Repository structure (selected)"
Write-Line "- Backend: src/main/java"
Write-Line "- DB migrations: src/main/resources/db/migration"
Write-Line "- Neo4j schema: src/main/resources/db/neo4j"
Write-Line "- UI (static SPA): src/main/resources/static"
Write-Line ""

Write-Line "## Markdown docs in /docs"
Write-Line ""
Get-ChildItem -Path (Join-Path $root 'docs') -Recurse -File -Include *.md |
  Where-Object { $_.FullName -notmatch '\\docs\\generated\\' } |
  Sort-Object FullName |
  ForEach-Object {
    $rel = $_.FullName.Substring($root.Path.Length + 1).Replace('\\','/')
    Write-Line "- [$rel](./$($_.FullName.Substring((Join-Path $root 'docs').Length + 1).Replace('\\','/')))"
  }

Write-Line ""
Write-Line "## Java packages (src/main/java)"
Write-Line ""
Get-ChildItem -Path (Join-Path $root 'src/main/java') -Recurse -Directory |
  Where-Object { $_.FullName -match '\\org\\aiopsanalysis(\\|$)' } |
  Sort-Object FullName |
  ForEach-Object {
    $pkg = $_.FullName.Substring((Join-Path $root 'src/main/java').Length + 1).Replace('\\','.')
    Write-Line "- $pkg"
  }

Write-Line ""
Write-Line "## Flyway migrations"
Write-Line ""
Get-ChildItem -Path (Join-Path $root 'src/main/resources/db/migration') -File -Filter 'V*__*.sql' |
  Sort-Object Name |
  ForEach-Object {
    Write-Line "- $($_.Name)"
  }

Write-Line ""
Write-Line "## UI pages (static/pages)"
Write-Line ""
Get-ChildItem -Path (Join-Path $root 'src/main/resources/static/pages') -Directory |
  Sort-Object Name |
  ForEach-Object {
    Write-Line "- $($_.Name)/"
  }

Write-Line ""
Write-Line "---"
Write-Line "Generated by scripts/generate-project-docs.ps1"
